name: CI
on:
  push:
  pull_request:
permissions:
  contents: read
  actions: read
jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run validations & tests
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          ./tests/run_all_validations.ps1
